services:
  open-jp-dao-python-server-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: open-jp-dao-python-server-dev
    container_name: open-jp-dao-python-server-dev
    tty: true
    volumes:
      - ../server:/usr/src/app
    ports:
      - "8001:8000"
