openapi: 3.0.0
info:
  title: track API
  version: '1.0'
  description: rails trackのAPI
servers:
  - url: 'http://localhost:3000'
tags:
  - name: sessions
    description: 認証
paths:
  '/apis/nonce':
    get:
      summary: nonce取得
      tags:
        - sessions
      operationId: get-nonce
      description: nonceを取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NonceResult'
          headers: {}
  '/apis/verify':
    post:
      summary: 検証
      tags:
        - sessions
      operationId: post-verify
      description: ユーザーを検証
      responses:
        '201':
          description: OK
          headers: {}
  '/api/ethereum/{chain_id}/address/{address}/ens':
    get:
      summary: ens取得
      tags:
        - sessions
      operationId: get-ens
      description: ensを取得する
      parameters:
        - in: path
          name: chain_id
          schema:
            type: integer
          required: true
          description: chain_id
        - in: path
          name: address
          schema:
            type: string
          required: true
          description: ethereum EOA
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnsResult'
          headers: {}
components:
  schemas:
    NonceResult:
      title: nonce_result
      properties:
        nonce:
          type: string
      required:
        - nonce
    EnsResult:
      title: ens_result
      properties:
        ens_name:
          type: string
      required:
        - ens_name
