# D = Steep::Diagnostic
#
# target :lib do
#   signature "sig"
#   ignore_signature "sig/test"
#
#   check "lib"                       # Directory name
#   check "path/to/source.rb"         # File name
#   check "app/models/**/*.rb"        # Glob
#   # ignore "lib/templates/*.rb"
#
#   # library "pathname"              # Standard libraries
#   # library "strong_json"           # Gems
#
#   # configure_code_diagnostics(D::Ruby.default)      # `default` diagnostics setting (applies by default)
#   # configure_code_diagnostics(D::Ruby.strict)       # `strict` diagnostics setting
#   # configure_code_diagnostics(D::Ruby.lenient)      # `lenient` diagnostics setting
#   # configure_code_diagnostics(D::Ruby.silent)       # `silent` diagnostics setting
#   # configure_code_diagnostics do |hash|             # You can setup everything yourself
#   #   hash[D::Ruby::NoMethod] = :information
#   # end
# end

# target :test do
#   unreferenced!                     # Skip type checking the `lib` code when types in `test` target is changed
#   signature "sig/test"              # Put RBS files for tests under `sig/test`
#   check "test"                      # Type check Ruby scripts under `test`
#
#   configure_code_diagnostics(D::Ruby.lenient)      # Weak type checking for test code
#
#   # library "pathname"              # Standard libraries
# end

target :app do
  # check "app", "lib" # 型チェック対象のRubyコードがあるディレクトリ
  # 実験的に導入
  check "lib/file_record/header.rb"
  check "app/models/ledger.rb"
  check "app/models/ledger_item.rb"
  check "app/services/csv_imports/ledger.rb"
  check "app/services/file_uploads/generate_master.rb"
  # check "app/models/files/ledger_import_csv.rb"
  # 　次はhas manyとかかな。
  # check "app/models/import_file.rb"
  signature "sig"   # RBSファイルがあるディレクトリ
  # 必要に応じて標準ライブラリの型定義などを追加
  # library "pathname"
end
