openapi: 3.0.0
info:
  title: track API
  version: '1.0'
  description: rails trackのAPI
servers:
  - url: 'http://localhost:3000'
tags:
  - name: sessions
    description: 認証
  - name: dollaryen
    description: ドル円
paths:
  /apis/sessions/nonce:
    get:
      summary: nonce取得
      tags:
        - sessions
      operationId: get-sessions-nonce
      description: nonceを取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsNonceResult'
          headers: {}
  /apis/sessions/signin:
    post:
      summary: ログイン(サインイン)
      tags:
        - sessions
      operationId: post-sessions-signin
      description: ユーザーログイン。ChainGateのverifyに接続します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '201':
          description: OK
          headers: {}
  /apis/sessions/verify:
    post:
      summary: 検証
      tags:
        - sessions
      operationId: post-sessions-verify
      description: ユーザーを検証
      responses:
        '201':
          description: OK
          headers: {}
  /apis/sessions/signout:
    post:
      summary: ログアウト
      tags:
        - sessions
      operationId: post-sessions-signout
      description: ログアウト
      responses:
        '201':
          description: OK
          headers: {}
  /apis/sessions/user:
    get:
      summary: ユーザー情報
      tags:
        - sessions
      operationId: get-sessions-user
      description: ユーザー情報取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsUserResponse'
          headers: {}
  /apis/dollaryen/transactions:
    get:
      summary: ドル円トランザクション一覧取得
      tags:
        - dollar_yens_transactions
      operationId: list-dollaryen--transactions
      description: ドル円トランザクション一覧取得
      responses:
        '201':
          description: OK
          headers: {}
    post:
      summary: ドル円トランザクションの保存
      tags:
        - dollar_yens_transactions
      operationId: post-dollaryen-transactions
      description: ドル円トランザクション保存
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DollarYenTransactionsRequestBody'
      responses:
        '201':
          description: OK
          headers: {}
  '/apis/dollaryen/transactions/:transaction_id':
    get:
      summary: ドル円トランザクション取得
      tags:
        - dollaryen
      operationId: show-dollaryen-transactions
      description: ドル円トランザクション取得
      responses:
        '201':
          description: OK
          headers: {}
  '/apis/dollaryen/transactions/csv_upload':
    post:
      summary: ドル円トランザクションcsvアップロード
      tags:
        - dollaryen
      operationId: csv-upload-dollaryen-transactions
      description: ドル円トランザクション取得
      responses:
        '204':
          description: created
          headers: {}
  '/apis/dollaryen/foreigne_exchange_gain':
    get:
      summary: ドル円為替差益取得
      tags:
        - dollar_yens_foreigne_exchange_gain
      operationId: foreigne_exchange_gain
      description: 為替差益取得
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DollarYensForeigneExchangeGainResponse'
          headers: {}
  /apis/dollar_yens:
    get:
      summary: ドル円取得
      tags:
        - dollar_yens
      parameters:
        - schema:
            type: string
          name: date
          in: query
          required: false
      operationId: dollar_yens_index
      description: ドル円取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DollarYensResponse'
          headers: {}
  /apis/dollar_yens/csv_import:
    post:
      summary: ドル円csvインポート
      tags:
        - dollar_yens
      operationId: csv-import-dollaryen
      description: ドル円csv import
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DollarYensCsvImportRequestBody'
      responses:
        '204':
          description: created
          headers: {}
  /apis/transaction_types:
    get:
      summary: 取引種別取得
      tags:
        - transaction_types
      operationId: transaction_types_index
      description: 取引種別取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionTypesResponse'
          headers: {}
  /apis/notifications/index:
    get:
      summary: 通知取得
      tags:
        - notifications
      operationId: notifications_index
      description: 通知取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationsIndexResponse'
          headers: {}
components:
  schemas:
    SessionsNonceResult:
      title: sessions_nonce_result
      properties:
        nonce:
          type: string
      required:
        - nonce
    SessionsUserResponse:
      title: sessions_user_result
      properties:
        address:
          type: string
        network:
          type: string
        last_login:
          type: string
    NotificationsIndexResponse:
      title: notifications_index
      properties:
        notification:
          type: object
          properties:
            id:
              type: string
            message:
              type: string     
    SigninRequest:
      title: ログイン(サインイン)リクエスト
      type: object
      description: サインイン
      properties:
        address:
          type: string
        kind:
          type: integer
        chain_id:
          type: integer
        message:
          type: string
        signature:
          type: string
        domain:
          type: string
    DollarYenTransactionsRequestBody:
      title: ドル円トランザクションリクエスト
      type: object
      description: ドル円トランザクション
      properties:
        date:
          type: string
        transaction_type_id:
          type: integer
        deposit_rate:
          type: number
        deposit_quantity:
          type: number
        withdrawal_quantity:
          type: number
        exchange_en:
          type: number
    DollarYensResponse:
      title: ドル円一覧結果
      properties:
        total:
          type: integer
        dolla_yens:
          items:
            type: object
            properties:
              date:
                type: string
              dollar_yen_nakane:
                type: string
      required:
        - total
        - dollar_yens
    DollarYensCsvImportRequestBody:
      title: ドル円csv importリクエスト
      properties:
        file:
          type: string
          format: binary
      required:
        - file
    DollarYensForeigneExchangeGainResponse:
      title: ドル円為替差益
      type: object
      properties:
        date:
          type: object
          properties:
            start_date:
              type: string
            end_date:
              type: string
        data:
          type: object
          properties:
            total:
              type: integer
            dollaryen_transactions:
              items:
                type: object
                properties:
                  date:
                    type: string
                  transaction_type_name:
                    type: string
                  withdrawal_rate:
                    type: number
                  withdrawal_quantity:
                    type: number
                  withdrawal_en:
                    type: number
        foreign_exchange_gain:
          type: number
    TransactionTypesResponse:
      title: 取引種別取得
      properties:
        total:
          type: integer
        transaction_types:
          items:
            type: object
            properties:
              name:
                type: string
              kind:
                type: string
              kind_name:
                type: string
      required:
        - total
        - transaction_types
