openapi: 3.0.0
info:
  title: track API
  version: '1.0'
  description: rails trackのAPI
servers:
  - url: 'http://localhost:3000'
tags:
  - name: sessions
    description: 認証
  - name: dollaryen
    description: ドル円
paths:
  /apis/sessions/nonce:
    get:
      summary: nonce取得
      tags:
        - sessions
      operationId: get-sessions-nonce
      description: nonceを取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsNonceResult'
          headers: {}
  /apis/sessions/signin:
    post:
      summary: ログイン(サインイン)
      tags:
        - sessions
      operationId: post-sessions-signin
      description: ユーザーログイン。ChainGateのverifyに接続します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '201':
          description: OK
          headers: {}
  /apis/sessions/verify:
    post:
      summary: 検証
      tags:
        - sessions
      operationId: post-sessions-verify
      description: ユーザーを検証
      responses:
        '201':
          description: OK
          headers: {}
  /apis/sessions/signout:
    post:
      summary: ログアウト
      tags:
        - sessions
      operationId: post-sessions-signout
      description: ログアウト
      responses:
        '201':
          description: OK
          headers: {}
  '/apis/dollaryen/transactions':
    get:
      summary: ドル円トランザクション一覧取得
      tags:
        - dollaryen
      operationId: list-dollaryen--transactions
      description: ドル円トランザクション一覧取得
      responses:
        '201':
          description: OK
          headers: {}
    post:
      summary: ドル円トランザクションの保存
      tags:
        - dollaryen
      operationId: post-dollaryen-transactions
      description: ドル円トランザクション保存
      responses:
        '201':
          description: OK
          headers: {}
  '/apis/dollaryen/transactions/:transaction_id':
    get:
      summary: ドル円トランザクション取得
      tags:
        - dollaryen
      operationId: show-dollaryen-transactions
      description: ドル円トランザクション取得
      responses:
        '201':
          description: OK
          headers: {}
  '/apis/dollaryen/transactions/csv_upload':
    post:
      summary: ドル円トランザクションcsvアップロード
      tags:
        - dollaryen
      operationId: csv-upload-dollaryen-transactions
      description: ドル円トランザクション取得
      responses:
        '204':
          description: created
          headers: {}
  '/apis/dollaryen/foreigne_exchange_gain':
    get:
      summary: ドル円為替差益取得
      tags:
        - dollaryen
      operationId: foreigne_exchange_gain
      description: 為替差益取得
      responses:
        '201':
          description: OK
          headers: {}
  /apis/dollar_yens/csv_import:
    post:
      summary: ドル円csvインポート
      tags:
        - dollaryen
      operationId: csv-import-dollaryen
      description: ドル円csv import
      responses:
        '204':
          description: created
          headers: {}
components:
  schemas:
    SessionsNonceResult:
      title: sessions_nonce_result
      properties:
        nonce:
          type: string
      required:
        - nonce
    SigninRequest:
      title: ログイン(サインイン)リクエスト
      type: object
      description: サインイン
      properties:
        address:
          type: string
        kind:
          type: integer
        chain_id:
          type: integer
        message:
          type: string
        signature:
          type: string
        domain:
          type: string
