.PHONY: dc_build dc_up dc_stop
dc_build:
	docker-compose -f .devcontainer/compose.yaml build
dc_up:
	docker-compose -f .devcontainer/compose.yaml up
dc_stop:
	docker-compose -f .devcontainer/compose.yaml stop