name: dependabot

version: 2
updates:
  - package-ecosystem: bundler
    directory: '/track'
    schedule:
      interval: monthly
      timezone: Asia/Tokyo
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - 'dependencies'
      - 'ruby'