name: track コードチェック&テスト

on:
  push:
    branches:
      - main
      - develop
      - feature/csv_rails
    paths-ignore:
      - contracts/*
      - backend/*
      - docs/*
      - .gitignore
      - '**.md'

jobs:
  scan_ruby:
    name: track check
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ["3.3.4"]
    steps:
      - name: change working-directory
        working-directory: track

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager



